Repository glideapps/glide-data-grid, pull requests merged in 2022-02, with the labels that each got.

#143 Add paddingRight and paddingBottom to scrollWidth and scrollHeight
  packages/core/src/scrolling-data-grid/scrolling-data-grid.tsx
Labels: enhancement, UI

#173 on finish editing callback added
  packages/core/src/data-editor/data-editor.test.tsx
  packages/core/src/data-editor/data-editor.tsx
Labels: bug

#183 Add support for custom target column when adding rows
  packages/core/src/data-editor/data-editor-beautiful.stories.tsx
  packages/core/src/data-editor/data-editor.tsx
  packages/core/src/data-grid/data-grid-types.ts
Labels: enhancement
